# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "code.cloudfoundry.org/clock",
  "code.cloudfoundry.org/locket",
  "code.cloudfoundry.org/locket/lock",
  "github.com/satori/go.uuid",
  "github.com/tedsuo/ifrit/grouper",
  "github.com/tedsuo/ifrit/sigmon"
]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.7.3"

[[constraint]]
  name = "github.com/carlescere/scheduler"
  revision = "ee74d2f83d82cd1d2e92ed3ec3dbaf162ca5ece5"

# Workaround for dep panic issue - https://github.com/golang/dep/issues/1799
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true
